### ISSUE TITLE
Не сохраняются json и image поля

### ISSUE THREAD

**Issue by Sckatik** [moonshine-software/layouts-field#1]
moonshine -   2.11.3
laravel - 10.48.7

В FormPage:

     Layouts::make('Content')
                ->addLayout('Текст', 'text', [
                    TinyMce::make('Name'),
                ])
                ->addLayout('Список', 'list', [
                    Json::make('Data', 'test')
                        ->onlyValue()
                ])
Скрины с ошибками:
https://disk.yandex.ru/i/CC47ZtEH96v-4A - админка
https://disk.yandex.ru/i/66nDpcAzQ3mHpw - ошибка
https://disk.yandex.ru/i/viRyPjvEfroXJQ - в бд

**Comment by Sckatik** [comment]
Хотелось бы, чтобы Layouts поддерживал все поля. Кроме полей со связями. Тк есть проекты в которых нужен именно такой конструктор полей.

**Comment by Sckatik** [comment]
картинка просто не сохраняется.

https://disk.yandex.ru/i/OcQBFOAm1SoqQQ - в бд вот такой json.

Пока что не разобрался. Как в moonshine, работает разбор и сохранение полей. 
И где это можно поправить. 
Подскажите в каком направлении копать?

**Comment by lee-to** [comment]
На неделе сделаю фикс

**Comment by Sckatik** [comment]
Спасибо. Нашел ещё один баг. Если сохранить запись и не заполнить ни один Layout.
https://disk.yandex.ru/i/F_gwr7xQf97lwQ
То возникает ошибка в MoonShine\Layouts\Fields\Layouts в методе resolveOnApply. 
$values возвращает значение bool false. И возникает ошибка - **Trying to access array offset on value of type bool**
Пофиксил так - добавил в данный метод строчку - `$values = !$values ? [] : $values;`
```
        return function ($item, $values) {
            $values = !$values ? [] : $values;
            $data = collect($values)->map(function ($value, $index) {
                $layout = $value['_layout'];
                unset($value['_layout']);

                return [
                    'key' => $index,
                    'name' => $layout,
                    'values' => $value,
                ];
            })->filter();

            data_set($item, $this->column(), $data);

            return $item;
        };
```

**Comment by lee-to** [comment]
Исправил в новом релизе но также необходимо обновить муншайн до 2.11.4 и сбросить кеш js
