### ISSUE TITLE
Поле CKEditor не работает

### ISSUE THREAD

**Issue by povly** [moonshine-software/layouts-field#11]
Используется такой код:
`Layouts::make('Описание', 'content')
                    ->addLayout('Блок информаций - заголовок', 'blocks', [
                        Text::make('Заголовок', 'title'),
                        Text::make('Заголовок для навигаций', 'title')
                            ->hint('Навигация на левой колонке, можете оставить пустым - поставится основной заголовок'),
                        CKEditor::make('Описание', 'text')->hideOnIndex(),
                    ]),`

Скрин:
![image](https://github.com/user-attachments/assets/a663ad5a-be20-44b7-80ab-acaf97adb78e)

По логике наверное из-за того что у нас layout изначально скрыт и СKEditor не может инициализировать. По умолчанию стоит класс hidden - display:none. Можно создать событие открытия шаблона на JS, и думаю с пакета CKEditor попросить поправить чтобы вызвали код в это событие)

**Comment by lee-to** [comment]
Это issue CKEditor а не этот пакет, пофиксил, в течении часа оформлю релиз
