### ISSUE TITLE
Проблема с casts

### ISSUE THREAD

**Issue by povly** [moonshine-software/layouts-field#3]
`protected $casts = [
        'content' => LayoutsCast::class,
    ];`

Если поставить casts, то в любом методе выдает такую ошибку - при добавлении, обновлении
![image](https://github.com/moonshine-software/layouts-field/assets/48402954/af07cd80-298c-45cd-9334-3aace524771b)

Если убрать casts:
1. Создание записи работает
2. Редактирование выдает ошибку SQL - неверный тип параметра

Пока нашел такое решение, поставил AsCollection::class вместо LayoutsCast::class и все работает
![image](https://github.com/moonshine-software/layouts-field/assets/48402954/c032cf96-a96f-4e0f-83ae-e068a4aa1093)

**Comment by lee-to** [comment]
Не смог воспроизвести а тип поля в таблице json nullable?

**Comment by lee-to** [comment]
Попробуй обновится до 0.2.0
Убедись что в таблице тип json
Очисти данные в таблице и попробуй с нуля

**Comment by lee-to** [comment]
@povly расшарь страницу ошибка (там есть кнопка share) и пришли сюда
