### ISSUE TITLE
Добавление блоков не работает в modal из поля HasMany

### ISSUE THREAD

**Issue by Siesta** [moonshine-software/layouts-field#6]
Если добавить поле layouts в FormPage которое открывается по кнопке Добавить в поле HasMany, то при попытке добавить блок возникает ошибка Field not found.

Как понял проблема в том что x-data='layouts(url)' инициализируется по родительскому ресурсу, в котором присутствует HasMany, а не по дочернему, который используется в HasMany.

resources/views/layouts.blade.php:
```php

<div x-data="layouts(
    `{{ $element->getAddRoute() }}`,
    `{{ $element->column() }}`
)"
    {{ $element->attributes() }}
>

```

src/Fields/Layouts.php:67

```php

    public function getAddRoute(): string
    {
        return route('moonshine.layouts-field.store', [
            'resourceUri' => moonshineRequest()->getResourceUri(),
            'pageUri' => moonshineRequest()->getPageUri(),
        ]);
    }

```

В общем, суммирую - поле цепляет url родительского ресурса, а не дочернего. И при запросе конечно же такого поля в родительском ресурсе не существует.

**Comment by lee-to** [comment]
Добавил небольшой фикс, если юзаете поле внутри HasMany то необходимо указать текущую страницу и ресурс самостоятельн

```php
Layouts::make('Content', 'content')->nowOn(page: $this->formPage(), resource: $this)
```
