### ISSUE TITLE
В layouts не работает поле File

### ISSUE THREAD

**Issue by Siesta** [moonshine-software/layouts-field#7]
Если добавить поле File через addLayout то файл не сохраняется. При это он якобы сохраняется, путь до файла присутствует, но самого файла как такового нет.
Если подключить File c диском s3, то ругается на ошибку удаления - 
Unable to delete file located at: .

**Comment by lee-to** [comment]
Проверил на последней версии мун и layouts и проблему не обнаружил
Тестировал на базовом поле File с диском public File::make('File')

**Comment by djnew** [comment]
![image](https://github.com/moonshine-software/layouts-field/assets/886244/e3758227-ac0b-41c4-9c23-75377516e917)
проблема с получанием оригинального значения с модели - вехние два дампа файл без лейаута(новый загружается)
нижние два дампа файл в лейауте

вот тут https://github.com/moonshine-software/moonshine/blob/2.x/src/Traits/Fields/FileTrait.php#L202 получает UploadedFile вместо значения

дампы ставил сюда https://github.com/moonshine-software/moonshine/blob/2.x/src/Traits/Fields/FileTrait.php#L228

![image](https://github.com/moonshine-software/layouts-field/assets/886244/4c33b5ad-1b1e-4669-9c8a-01c7067a1a10)


ошибка выкидывается так как в методе https://github.com/moonshine-software/moonshine/blob/2.x/src/Traits/Fields/FileDeletable.php#L43 нет проверки на существование файла и в public диске это работает, s3 выдает ошибку так как $fileName пустой

**Comment by lee-to** [comment]
Я так понял проблема решена
